### ISSUE TITLE
Create a crawler to retrieve lyrics.

### ISSUE THREAD

**Issue by bernardosulzbach** [mafagafogigante/lyric-guesser#1]
I couldn't find one API that offered full lyrics for free, so I will likely write a spider eventually and get what I want from their sites.

**Comment by forstad** [comment]
Which site are you talking about? I am trying to get familiar with Python and would like to help you with your project ;)

**Comment by bernardosulzbach** [comment]
I appreciate the help. Any site you want to crawl. If you are experienced with webcrawlers this would save me some time. I will learn more about them in the future, when the need arises. AZ Lyrics seems good enough and it should be reasonably straightforward to parse.

**Comment by bernardosulzbach** [comment]
This has been done. Future work will be on my own and behind closed doors.
